version: '3.8'

services:
  typesense:
    image: typesense/typesense:29.0
    container_name: typesense-ecommerce
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # Configuraciones para datasets grandes
      - TYPESENSE_ENABLE_CORS=true
      - TYPESENSE_LOG_LEVEL=info
    volumes:
      - typesense_data:/data
    restart: unless-stopped
    # Configuración de recursos para datasets grandes
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  typesense_data:
    driver: local 